# Site Settings
title:               "Manuel Guilbault"
#tagline:             ""
description:         ""
baseurl:             ""
url:                 "https://manuel-guilbault.github.io"
paginate:            5
author:
  name:              "Manuel Guilbault"
  email:             "manuel.guilbault@gmail.com"
  twitter:           "manuguilbault"
  github:            "manuel-guilbault"
  linkedin:          "manuel-guilbault"
github:
  url:               "https://manuel-guilbault.github.io"
google:
  analytics:
    propertyId:      "UA-90742674-1"
disqus:
  handler:           "manuel-guilbault-github-io"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
