# Site Settings
title:               "Manuel Guilbault"
tagline:             ""
description:
baseurl:             ""
url:                 "https://manuel-guilbault.github.io"
github:
  url:               "https://manuel-guilbault.github.io"
google:
  analytics:
    propertyId:      "UA-90742674-1"
author:
  name:              "Manuel Guilbault"
  email:             "manuel.guilbault@gmail.com"
  twitter:           "manuguilbault"
  github:            "manuel-guilbault"
  linkedin:          "manuel-guilbault"
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
