# Site Settings
title:               "Manuel Guilbault's Blog"
#tagline:             ""
description:         ""
baseurl:             ""
url:                 "http://manuelguilbault.com"
paginate:            5
collections:
  posts:
    output:          true
    permalink:       /blog/:year/:month/:day/:title/
  talks:
    output:          true
    permalink:       /talks/:year/:month/:day/:title/

# ID & 3rd parties integration
author:
  name:              "Manuel Guilbault"
  email:             "manuel.guilbault@gmail.com"
  twitter:           "manuguilbault"
  github:            "manuel-guilbault"
  linkedin:          "manuel-guilbault"
google:
  analytics:
    propertyId:      "UA-90742674-1"
disqus:
  handler:           "manuelguilbault"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
